-d /home/loz/Development/8bitFPGA/sap_1/impl/gwsynthesis/gowin.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/loz/Development/8bitFPGA/sap_1/tangnano9k.cst
-cfg /home/loz/Development/8bitFPGA/sap_1/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
